"""Generate static, tree-shakable React icons from the reviewed local SVG selection.

Run from apps/web: python scripts/generate-streamline-icons.py
Sources and adaptations are recorded in components/icons/manifest.json.
No network access, runtime SVG parsing, or untrusted HTML injection.
"""
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1] / 'components/icons'
manifest = json.loads((root / 'manifest.json').read_text(encoding='utf-8'))
allowed = {'path', 'g', 'circle', 'ellipse', 'rect', 'line', 'polyline', 'polygon'}
attributes = {'d', 'fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin',
              'opacity', 'cx', 'cy', 'rx', 'ry', 'x', 'y', 'x1', 'x2', 'y1', 'y2',
              'width', 'height', 'r', 'points', 'transform', 'fill-rule', 'clip-rule', 'stroke-miterlimit'}

def jsx(node):
    tag = node.tag.split('}')[-1]
    assert tag in allowed, tag
    props = []
    for key, value in node.attrib.items():
        assert key in attributes, key
        if key == 'stroke' and value in ('var(--sl-c-000000,#000000)', '#000000'):
            continue  # inherit the component's color and selected/disabled states
        if key == 'stroke-width':
            assert value == '1'
            continue
        value = value.replace('var(--sl-c-000000,#000000)', 'currentColor')
        if value == '#000000': value = 'currentColor'
        assert 'url(' not in value and 'var(' not in value, value
        key = re.sub(r'-([a-z])', lambda m: m[1].upper(), key)
        props.append(f'{key}={json.dumps(value)}')
    prefix = '<' + tag + (' ' + ' '.join(props) if props else '')
    return prefix + ('>' + ''.join(jsx(child) for child in node) + '</' + tag + '>' if len(node) else ' />')

output = ['''// Generated by scripts/generate-streamline-icons.py; edit manifest/sources instead.
// Streamline Ultimate Light — CC BY 4.0. See ATTRIBUTION.md.
import type { ReactNode, SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };

export function createIcon(name: string, artwork: ReactNode, viewBox = "0 0 24 24", grid = 24) {
  return function Icon({ size = 24, strokeWidth = 1.25, color = "currentColor", className, children, ...props }: IconProps) {
    return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size}
      viewBox={viewBox} fill="none" stroke={color} strokeWidth={typeof strokeWidth === "number" ? strokeWidth * grid / 24 : strokeWidth}
      strokeLinecap="round" strokeLinejoin="round" focusable="false"
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props} className={["streamline-icon", className].filter(Boolean).join(" ")}
      data-streamline-icon={name}>{artwork}{children}</svg>;
  };
}
''']
for name, entry in manifest.items():
    tree = ET.fromstring((root / entry['file']).read_text(encoding='utf-8'))
    source_box = tree.attrib['viewBox']
    dimensions = [float(v) for v in source_box.split()]
    assert dimensions[2] == dimensions[3] and dimensions[2] in (24, 25)
    nodes = list(tree)
    adaptation = entry.get('adaptation')
    box, grid = source_box, int(dimensions[2])
    if adaptation == 'single-chevron':
        nodes[0].set('d', nodes[0].get('d').split('M12.3')[0])
        nodes[0].set('transform', 'translate(5.85 0)')
    elif adaptation == 'status-circle':
        nodes = [nodes[1]]
        if entry.get('centerDot'):
            nodes.append(ET.Element('circle', {'cx':'12','cy':'12','r':'3','fill':'currentColor','stroke':'none'}))
    elif adaptation == 'unframed-search':
        nodes, box, grid = [nodes[0]], '4.5 4.5 15 15', 15
    elif adaptation == 'unframed-close':
        nodes[0].set('d', 'M7 7' + nodes[0].get('d').split('M7 7')[1])
        box, grid = '4 4 16 16', 16
    elif adaptation == 'unframed-minus':
        nodes[0].set('d', 'M18 12L6 12')  # the source's subtract stem, without its circle
        box, grid = '3 3 18 18', 18
    elif adaptation == 'unframed-check':
        nodes, box, grid = [nodes[0]], '5 5 14 14', 14
    elif adaptation == 'unframed-message':
        nodes, box, grid = [nodes[1]], '4 3 18 18', 18
    body = ''.join(jsx(node) for node in nodes)
    if 'rotate' in entry:
        body = f'<g transform="rotate({entry["rotate"]} 12 12)">{body}</g>'
    args = '' if grid == 24 else f', "{box}", {grid}'
    module = f'// Generated Streamline Ultimate Light — CC BY 4.0. See ATTRIBUTION.md.\n// {entry["sourceName"]}; {entry["hash"]}\nimport {{ createIcon }} from "./create-icon";\nexport const {name} = createIcon("{name}", <>{body}</>{args});\n'
    (root / f'{name}.tsx').write_text(module, encoding='utf-8')
(root / 'create-icon.tsx').write_text(output[0], encoding='utf-8')
(root / 'index.tsx').write_text('// Compatibility exports; application consumers import individual icon modules.\n' + '\n'.join(f'export {{ {name} }} from "./{name}";' for name in manifest) + '\nexport type { IconProps } from "./create-icon";\n', encoding='utf-8')
print(f'Generated {len(manifest)} named icons from {len(set(x["file"] for x in manifest.values()))} source SVGs.')
