import {test,expect} from '@playwright/test';
test.beforeEach(async({context})=>{await context.addCookies([{name:'dli_locale',value:'en',url:'http://127.0.0.1:3100'}]);});
test('sidebar collapse preserves the shell, persists and respects reduced motion',async({page})=>{
 await page.goto('/dashboard');
 await expect(page.locator('.continuity-sidebar')).toBeVisible();
 await page.evaluate(()=>document.querySelector('main')!.setAttribute('data-retained','yes'));
 await page.getByRole('button',{name:'Collapse menu',exact:true}).click();
 await expect(page.locator('.continuity-shell')).toHaveClass(/continuity-collapsed/);
 await page.locator('.continuity-sidebar a[href="/drug-letters"]').click();
 await expect(page.locator('.letter-row')).toHaveCount(20);
 await expect(page.locator('main')).toHaveAttribute('data-retained','yes');
 await page.reload();
 await expect(page.locator('.continuity-shell')).toHaveClass(/continuity-collapsed/);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.getByRole('button',{name:'Expand menu',exact:true}).focus();
 await page.keyboard.press('Enter');
 await expect(page.locator('.continuity-shell')).not.toHaveClass(/continuity-collapsed/);
 expect(await page.locator('.continuity-sidebar').evaluate(node=>node.getAnimations().length)).toBe(0);
 await expect(page.getByRole('button',{name:'Collapse menu',exact:true})).toBeFocused();
});
