// Generated by scripts/generate-streamline-icons.py; edit manifest/sources instead.
// Streamline Ultimate Light — CC BY 4.0. See ATTRIBUTION.md.
import type { ReactNode, SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };

export function createIcon(name: string, artwork: ReactNode, viewBox = "0 0 24 24", grid = 24) {
  return function Icon({ size = 24, strokeWidth = 1.25, color = "currentColor", className, children, ...props }: IconProps) {
    return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size}
      viewBox={viewBox} fill="none" stroke={color} strokeWidth={typeof strokeWidth === "number" ? strokeWidth * grid / 24 : strokeWidth}
      strokeLinecap="round" strokeLinejoin="round" focusable="false"
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props} className={["streamline-icon", className].filter(Boolean).join(" ")}
      data-streamline-icon={name}>{artwork}{children}</svg>;
  };
}
